FROM continuumio/miniconda3:4.6.14

RUN conda install --yes --freeze-installed \
    nomkl \
    numpy==1.16.3 \
    pandas==0.24.2 \
    flask=1.1.1 \
    && conda clean -afy

RUN pip install flask-bootstrap==3.3.7.1 frozen-flask==0.15

EXPOSE 80
EXPOSE 8080

WORKDIR /app
ENTRYPOINT ["/bin/bash", "./build.sh"]
# ENTRYPOINT ["/bin/bash"]
